name: Publish Any Commit
# from https://github.com/stackblitz-labs/pkg.pr.new?tab=readme-ov-file
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm build

      - run: npx pkg-pr-new publish --template '.'
